services:
  flask_app:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
      MYSQL_DB: bookstore_db

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: techpro1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: techproed
      MYSQL_PASSWORD: techpro1234
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
